name: flask_app_dev_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - flask
  - flask-cors
  - boto3
  - requests
  - pymysql
  - sshtunnel
  - paramiko
  - python-dotenv
  - pip
  # Development dependencies
  - argparse
  - pytest
  - jupyter
  # Pip dependencies
  - pip:
      - python-dotenv
